### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by eaglerayp** [ansyun/dpdk-nginx#1]
in auto/make line 20:

```
if [ $RTE_ODP ];
then
    ODP_PATH=$RTE_ODP
else
    echo "Please define RTE_SDK environment variable"
    exit 1
fi
```

echo should be `echo "Please define RTE_ODP environment variable"`

**Comment by jiakai1000** [comment]
Yes, and all environment variables used should be checked !
https://github.com/opendp/dpdk-nginx/commit/f1da4e1d2614d5ce8c4b281f91af1831294fce39
