### ISSUE TITLE
unrecognized relocation (0x2a) in section `.text'

### ISSUE THREAD

**Issue by raoping2017** [ansyun/dpdk-nginx#11]
/usr/bin/ld: /home/shuzilm/workspace/dpdk-ans/librte_ans/librte_ans.a(ans_init.o): unrecognized relocation (0x2a) in section `.text'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
/home/shuzilm/workspace/dpdk-stable-16.11.1/mk/rte.app.mk:231: recipe for target 'ans' failed
make[1]: *** [ans] Error 1
/home/shuzilm/workspace/dpdk-stable-16.11.1/mk/rte.extapp.mk:42: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by bluenet13** [comment]
please upgrade binutils, and also upgrade gcc to 5.4 version.

**Comment by raoping2017** [comment]
I already upgraded binutils to newest, and gcc is 5.4 version now, but the question is still exist.why?

**Comment by raoping2017** [comment]
Upgraded binutils to binutils-2.28, problem sloved.
