### ISSUE TITLE
2017/04/28 18:59:09 [alert] 18832#0: socketpair() failed while spawning "worker process"

### ISSUE THREAD

**Issue by raoping2017** [ansyun/dpdk-nginx#12]
sudo /opt/nginx-dpdk/sbin/nginx -c /opt/nginx-dpdk/conf/nginx.conf
EAL: Detected 4 lcore(s)
EAL: WARNING: Address Space Layout Randomization (ASLR) is enabled in the kernel.
EAL:    This may cause issues with mapping memory into secondary processes
USER8: LCORE[-1] anssock any lcore id 0xffffffff 
USER8: LCORE[0] anssock app id: 18830 
USER8: LCORE[0] anssock app name: nginx 
USER8: LCORE[0] anssock app bind lcoreId: 1 
USER8: LCORE[0] anssock app bind queueId: 0 
USER8: LCORE[0] anssock app lcoreId: 0 
skip linux fd 5 
2017/04/28 18:59:09 [notice] 18830#0: using the "epoll" event method
2017/04/28 18:59:09 [warn] 18830#0: 10240 worker_connections exceed open file resource limit: 1024
2017/04/28 18:59:09 [notice] 18830#0: nginx/1.9.5
2017/04/28 18:59:09 [notice] 18830#0: built by gcc 5.4.0 (GCC) 
2017/04/28 18:59:09 [notice] 18830#0: OS: Linux 4.2.0-36-generic
2017/04/28 18:59:09 [notice] 18830#0: getrlimit(RLIMIT_NOFILE): 1024:65536
2017/04/28 18:59:09 [notice] 18832#0: start worker processes
2017/04/28 18:59:09 [alert] 18832#0: socketpair() failed while spawning "worker process"
2017/04/28 18:59:09 [alert] 18832#0: socketpair() failed while spawning "worker process"

**Comment by bluenet13** [comment]
Please refer to dpdk-nginx config file

**Comment by raoping2017** [comment]
#user  nobody;
worker_processes  2;

error_log  stderr debug;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;
#master_process off;
#daemon on;

events {
    worker_connections  10240;
    multi_accept on;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        off;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       8080  default_server; #reuseport;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            root   html;
            index  index.html index.htm;
	    lingering_close off;
        }
        
        # proxy /proxy/ to http://10.0.0.10:80/   
				#location /proxy/ {
        #     proxy_pass http://10.0.0.10:80/;
        #}

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        # proxy the PHP scripts to Apache listening on 127.0.0.1:80
        #
        #location ~ \.php$ {
        #    proxy_pass   http://127.0.0.1;
        #}

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        #location ~ \.php$ {
        #    root           html;
        #    fastcgi_pass   127.0.0.1:9000;
        #    fastcgi_index  index.php;
        #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
        #    include        fastcgi_params;
        #}

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #    deny  all;
        #}
    }


    # another virtual host using mix of IP-, name-, and port-based configuration
    #
    #server {
    #    listen       8000;
    #    listen       somename:8080;
    #    server_name  somename  alias  another.alias;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}


    # HTTPS server
    #
    #server {
    #    listen       443 ssl;
    #    server_name  localhost;

    #    ssl_certificate      cert.pem;
    #    ssl_certificate_key  cert.key;

    #    ssl_session_cache    shared:SSL:1m;
    #    ssl_session_timeout  5m;

    #    ssl_ciphers  HIGH:!aNULL:!MD5;
    #    ssl_prefer_server_ciphers  on;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}

}

**Comment by bluenet13** [comment]
change your worker_processes  as 1

**Comment by raoping2017** [comment]
set worker_processes is 1,but question still exist

EAL: Detected 4 lcore(s)
EAL: WARNING: Address Space Layout Randomization (ASLR) is enabled in the kernel.
EAL:    This may cause issues with mapping memory into secondary processes
USER8: LCORE[-1] anssock any lcore id 0xffffffff 
USER8: LCORE[0] anssock app id: 23715 
USER8: LCORE[0] anssock app name: nginx 
USER8: LCORE[0] anssock app bind lcoreId: 1 
USER8: LCORE[0] anssock app bind queueId: 0 
USER8: LCORE[0] anssock app lcoreId: 0 
skip linux fd 5 
2017/05/02 14:08:35 [notice] 23715#0: using the "epoll" event method
2017/05/02 14:08:35 [warn] 23715#0: 10240 worker_connections exceed open file resource limit: 1024
2017/05/02 14:08:35 [notice] 23715#0: nginx/1.9.5
2017/05/02 14:08:35 [notice] 23715#0: built by gcc 5.4.0 (GCC) 
2017/05/02 14:08:35 [notice] 23715#0: OS: Linux 4.2.0-36-generic
2017/05/02 14:08:35 [notice] 23715#0: getrlimit(RLIMIT_NOFILE): 1024:65536
2017/05/02 14:08:35 [notice] 23717#0: start worker processes
2017/05/02 14:08:35 [alert] 23717#0: socketpair() failed while spawning "worker process"

**Comment by bluenet13** [comment]
refer to this nginx conf  https://github.com/opendp/dpdk-nginx/blob/master/conf/nginx.conf
maybe you shall set "master_process off;"

**Comment by raoping2017** [comment]
ok
