### ISSUE TITLE
NO reply from the dpdk-nginx server

### ISSUE THREAD

**Issue by gonghuahill** [ansyun/dpdk-nginx#14]
env  vsphere6.5 , sriov with pci attach to vm ; 
centos  [root@localhost ab]# uname -a
Linux localhost.localdomain 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
what's wrong , should I set the vlan tag in os to connect to the physical switch ?
### ans 
[root@localhost ans]# ./build/ans -c 0x2 -n 1 -- -p 0x1 --config="(0,0,1)"
EAL: Detected 4 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: PCI device 0000:0b:00.0 on NUMA socket -1
EAL:   probe driver: 15ad:7b0 net_vmxnet3
EAL: PCI device 0000:13:00.0 on NUMA socket -1
EAL:   probe driver: 8086:10ed net_ixgbe_vf
EAL: PCI device 0000:1b:00.0 on NUMA socket -1
EAL:   probe driver: 8086:10ed net_ixgbe_vf
param nb 1 ports 2
port id 0

Start to Init port
         port 0:
         port name net_ixgbe_vf:
         max_rx_queues 1: max_tx_queues:1
         rx_offload_capa 0xf: tx_offload_capa:0x3f
         Creating queues: rx queue number=1 tx queue number=1...
PMD: ixgbevf_dev_configure(): VF can't disable HW CRC Strip
         MAC Address:00:0C:29:BB:6C:B1
         Deault-- tx pthresh:32, tx hthresh:0, tx wthresh:0, txq_flags:0xf01
         lcore id:1, tx queue id:0, socket id:0
         Conf-- tx pthresh:32, tx hthresh:0, tx wthresh:0, txq_flags:0x0

Skipping disabled port 1
Allocated mbuf pool on socket 0, mbuf number: 16384

Initializing rx queues on lcore 1 ...
Default-- rx pthresh:8, rx hthresh:8, rx wthresh:0
port id:0, rx queue id: 0, socket id:0
Conf-- rx pthresh:8, rx hthresh:8, rx wthresh:4

core mask: 2, sockets number:1, lcore number:1
start to init ans
USER8: LCORE[1] lcore mask 0x2
USER8: LCORE[1] lcore id 1 is enable
USER8: LCORE[1] lcore number 1
USER1: rte_ip_frag_table_create: allocated of 25165952 bytes at socket 0
USER8: LCORE[1] UDP layer init successfully, Use memory:4194304 bytes
USER8: LCORE[1] TCP hash table init successfully, tcp pcb size 448 total size 58                                                                              720256
USER8: LCORE[1] so shm memory 16777216 bytes, so number 131072,  sock shm size 1                                                                              28 bytes
USER8: LCORE[1] Sock init successfully, allocated of 41943040 bytes
add eth0 device
USER8: LCORE[1] Interface eth0 if_capabilities: 0x3f
add IP 200000a on device eth0

Skipping disabled port 1
Show interface

eth0    HWaddr 00:0c:29:bb:6c:b1
                inet addr:10.0.0.2
                inet addr:255.255.255.0
add static route

Destination             Gateway         Netmask                 Flags          I                                                                              face
10.0.0.0                *               255.255.255.0           U C            0
10.0.0.5                *               255.255.255.255         U H L          0
10.10.0.0               10.0.0.5                255.255.255.0           U G    0

USER8: LCORE[-1] ANS mgmt thread startup

Checking link status done
Port 0 Link Up - speed 10000 Mbps - full-duplex
USER8: main loop on lcore 1
USER8:  -- lcoreid=1 portid=0 rxqueueid=0
nb ports 2 hz: 2394456318
##### nginx 
[root@localhost dpdk-nginx]# ./objs/nginx
EAL: Detected 4 lcore(s)
EAL: WARNING: Address Space Layout Randomization (ASLR) is enabled in the kernel.
EAL:    This may cause issues with mapping memory into secondary processes
USER8: LCORE[-1] anssock any lcore id 0xffffffff
USER8: LCORE[0] anssock app id: 24558
USER8: LCORE[0] anssock app name: nginx
USER8: LCORE[0] anssock app bind lcoreId: 1
USER8: LCORE[0] anssock app bind queueId: 0
USER8: LCORE[0] anssock app lcoreId: 0
USER8: LCORE[0] mp ops number 5, mp ops index: 0
skip linux fd 5
2017/09/12 14:03:42 [notice] 24558#0: using the "epoll" event method
2017/09/12 14:03:42 [notice] 24558#0: nginx/1.9.5
2017/09/12 14:03:42 [notice] 24558#0: built by gcc 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC)
2017/09/12 14:03:42 [notice] 24558#0: OS: Linux 3.10.0-514.el7.x86_64
2017/09/12 14:03:42 [notice] 24558#0: getrlimit(RLIMIT_NOFILE): 1024:4096
###  ab

[root@localhost ab]#  ab -n 30000 -c 500 10.0.0.2:80/
This is ApacheBench, Version 2.3 <$Revision: 1430300 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 10.0.0.2 (be patient)
apr_pollset_poll: The timeout specified has expired (70007)

**Comment by bluenet13** [comment]
Check if you can ping 10.0.0.2 successfully from you ab PC.
