### ISSUE TITLE
nginx cannot connect

### ISSUE THREAD

**Issue by eaglerayp** [ansyun/dpdk-nginx#2]
I have built and run nginx with opendp successfully.
However, once connected to http://0.0.0.0:80/ (no matter by browser or ab), the nginx program just shutdown without any sign. (opendp still running)

below is my nginx start log:

```
2015/11/03 18:18:58 [alert] 8889#0: listen() to 0.0.0.0:80, backlog 511 failed, ignored (57: Invalid slot)
2015/11/03 18:18:58 [notice] 8889#0: using the "epoll" event method
2015/11/03 18:18:58 [notice] 8889#0: nginx/1.9.5
2015/11/03 18:18:58 [notice] 8889#0: built by gcc 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04) 
2015/11/03 18:18:58 [notice] 8889#0: OS: Linux 3.13.0-37-generic
2015/11/03 18:18:58 [notice] 8889#0: getrlimit(RLIMIT_NOFILE): 1048576:1048576
$   // you can see program shutdown without ctrl+c
```

Is problem of listen backlog?

**Comment by jiakai1000** [comment]
I haven't met this problem before, you can run nginx with gdb to see what happend if nginx crashed.

**Comment by eaglerayp** [comment]
After installing new OS (ubuntu14.04), I can build successfully.
Maybe there are some driver/kernel problem since I have tested some library. 
Let's close the issue.
