### ISSUE TITLE
is proxy_pass works?

### ISSUE THREAD

**Issue by whoisjohngalt** [ansyun/dpdk-nginx#6]
is proxy_pass works for load balancing with dpdk-nginx?
I can get local page. But upstream not working. In debug log i can see "failed while conecting upstream".

**Comment by whoisjohngalt** [comment]
In error.log and debug level.

**Comment by bluenet13** [comment]
Please share the all detail nginx log and conf file, and your test steps.
I can't get the log "failed while conecting upstream" in dpdk-nginx.

**Comment by bluenet13** [comment]
Sorry, some issue in opendp_module.c, connect isn't adapted to netdpsock, i will fix it.

**Comment by whoisjohngalt** [comment]
Thanks. I will wait for it.

**Comment by whoisjohngalt** [comment]
i fixed connection function and getsockopt fucntion, and now its works!

**Comment by bluenet13** [comment]
Some problem in opendp, when connect, opendp will change the error code, so nginx report connect fail. now i have fixed it. but there is another issue, i will fix tomorrow.
2016/03/31 20:58:52 [alert] 31272#0: *1 readv() failed (9: Bad file descriptor)                                                                                                                                                              while reading upstream, client: 2.2.2.5, server: localhost, request: "GET /proxy                                                                                                                                                             / HTTP/1.0", upstream: "http://5.5.5.5:80/proxy/", host: "2.2.2.2"

**Comment by bluenet13** [comment]
nginx proxy_pass is supported now, please clone dpdk-odp and dpdk-nginx code, and try it again.
For dpdk-nginx, add connect and readv api.
For dpdk-odp, fix some socket bugs.

**Comment by whoisjohngalt** [comment]
Its worked if add getsockopt fucntion. But there is another issue. If we transfer to proxy_pass file like few kilobytes size dpdk-nginx falls.

**Comment by bluenet13** [comment]
Cloud you please share you opendp_module.c file and the detail steps for the failed case. My email: zimeiw@163.com.
Thanks.

**Comment by whoisjohngalt** [comment]
Thanks.
